models/project.py
import datetime
import uuid
from typing import Dict

from common.Database import Database


class Project:
    collection = "projects"

    def __init__(self, name: str, time: datetime, weight: float, path: str, _id: str = None):
        self.name = name
        self.time = time
        self.weight = weight
        self.path = path
        self.collection = "projects"
        self._id = _id or uuid.uuid4().hex

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "time": self.time,
            "weight": self.weight,
            "path": self.path
        }

    def save_to_mongo(self):
        Database.update(self.collection, {"_id": self._id}, self.json())

    def remove_from_mongo(self):
        Database.remove(self.collection, {"_id": self._id})

    @classmethod
    def find_one_by(cls, attribute, value):
        result = Database.find_one(cls.collection, {attribute: value})
        return cls(**result) if result else None

    @classmethod
    def find_many_by(cls, attribute, value):
        result = Database.find(cls.collection, {attribute: value})
        return [cls(**elem) for elem in result] if result else None

    @classmethod
    def get_by_id(cls, _id):
        return cls.find_one_by("_id", _id)

    @classmethod
    def all(cls, skip=0, limit=0):
        result = Database.find("projects", {}).sort("name").skip(skip).limit(limit)
        return [cls(**project) for project in result] if result else None

    @classmethod
    def get_by_search(cls, parameter):
        result = Database.DATABASE[cls.collection].find(
            {"$or":
                [
                    {"name": {"$regex": parameter, "$options": 'i'}},
                    {"path": {"$regex": parameter, "$options": 'i'}}
                ]
            })
        return [cls(**elem) for elem in result] if result else None

views/projects.py
import re
import datetime

from flask import Blueprint, request, render_template, make_response, redirect, url_for, flash, Markup, current_app
from flask_paginate import Pagination, get_page_parameter
from werkzeug.utils import secure_filename

from models.project import Project
from models.user.decorators import requires_login, requires_admin
from common.utils import Utils
import os

project_blueprints = Blueprint("projects", __name__)

view = {
    "title": "Projects",
    "icon": "fa-puzzle-piece",
    "name": "projects",
    "nav_on": True,
    "search_on": False
}


@project_blueprints.route('/', methods=['GET'])
@requires_login
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)

    per_page = 8
    offset = (page - 1) * per_page if page > 0 else 1

    projects = Project.all(offset, per_page)
    counter = len(Project.all())

    view['title'] = "Projects"
    view['search_on'] = True

    search = False
    q = request.args.get('q')
    if q:
        search = True

    pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                            search=search, record_name='projects')

    return render_template('projects/index.html', projects=projects, pagination=pagination, view=view)


@project_blueprints.route('/search', methods=['POST'])
@requires_login
def search():
    if request.method == 'POST' and request.form['parameter'] != "":
        parameter = request.form['parameter']
        projects = Project.get_by_search(parameter)

        page = request.args.get(get_page_parameter(), type=int, default=1)
        counter = len(projects)
        per_page = counter if counter > 0 else 1
        offset = counter

        view['title'] = "Projects"
        view['search_on'] = True

        search = False
        q = request.args.get('q')
        if q:
            search = True

        pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                                search=search, record_name='projects')

        return render_template('projects/index.html', projects=projects, pagination=pagination, view=view)
    else:
        return redirect(url_for('projects.index'))


@project_blueprints.route('/new', methods=['GET', 'POST'])
@requires_login
def new_project():
    if request.method == 'POST':
        file = request.files['file']

        temp_path = current_app.config.get('TEMPORAL_FOLDER', '')

        if not os.path.exists(temp_path):
            os.makedirs(temp_path)

        file_url_temp = os.path.join(temp_path, secure_filename(file.filename))
        file.save(file_url_temp)

        name = re.sub('.gcode', '', str(file.filename))
        time = Utils.get_print_time(file_url_temp)
        weight = Utils.get_weight(file_url_temp)

        upd_project = Project.find_one_by("name", name)
        if upd_project:

            upload_path = current_app.config.get('UPLOAD_FOLDER', '')

            if not os.path.exists(upload_path):
                os.makedirs(upload_path)

            file_url = os.path.join(upload_path, secure_filename(file.filename))
            os.replace(file_url_temp, file_url)
            path = file_url

            upd_project.name = name
            upd_project.time = time
            upd_project.weight = weight
            upd_project.path = path

            upd_project.save_to_mongo()
            return "The project was updated!", 200
        else:
            upload_path = current_app.config.get('UPLOAD_FOLDER', '')

            if not os.path.exists(upload_path):
                os.makedirs(upload_path)

            file_url = os.path.join(upload_path, secure_filename(file.filename))
            os.replace(file_url_temp, file_url)
            path = file_url
            Project(name, time, weight, path).save_to_mongo()
            return "Upload project successfully", 200
    else:
        view['title'] = "New Project"
        view['search_on'] = False
        return render_template('projects/dragndrop.html', view=view)


@project_blueprints.route('/edit/<string:project_id>', methods=['GET', 'POST'])
@requires_login
def edit_project(project_id):
    project = Project.get_by_id(project_id)

    if request.method == 'POST':
        project.name = request.form['name']
        project.time = request.form['time']
        project.weight = request.form['weight']
        project.path = request.form['path']

        x_project = Project.find_one_by("name", project.name)
        if x_project is not None:
            if x_project._id != project_id:
                message = Markup('<i class="fa fa-warning"></i> Error: The project cannot be created, already exist.')
                flash(message, 'warning')
                view['title'] = "Edit project"
                view['search_on'] = False
                return render_template('projects/edit_project.html', project=project, view=view)

        project.save_to_mongo()
        flash('The project was updated!', 'success')
        return redirect(url_for('projects.index'))
    else:
        view['title'] = "Edit project"
        view['search_on'] = False
        return render_template('projects/edit_project.html', project=project, view=view)


@project_blueprints.route('/delete/<string:project_id>', methods=['GET'])
@requires_login
@requires_admin
def remove_project(project_id):
    project = Project.get_by_id(project_id)
    file_url = project.path
    os.remove(file_url)
    project.remove_from_mongo()
    flash('The project was deleted!', 'danger')
    return redirect(url_for('projects.index'))

templates/projects/dragndrop.html
{% extends "base.html" %}
{% block  content%}
    {{ dropzone.load_css() }}
    {{ dropzone.load_js() }}
    <section class="dragndrop">
        <form action="/projects/new" method="post" class="dropzone dz-clickable mb-5" id="myDropzone" enctype="multipart/form-data">
            <div class="dz-default dz-message justify-content-center align-items-center pt-4">
                <i class="fa fa-cloud-upload fa-5x mb-3 text-success" aria-hidden="true"></i><br>
                <span>Choose your gcodes or drag it here to upload</span><br>
                <button type="button" class="btn btn-success mt-3">Upload files</button>
            </div>
        </form>
        <center><a class="btn btn-success" href="{{url_for('projects.index')}}"> Go back </a></center>
        {{ dropzone.config() }}
    </section>
    {{ dropzone.style('border: 2px dashed #45B449; font-size:18px ;margin: 10%; min-height: 400px;') }}
{% endblock %}

templates/projects/edit_project.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-project-form">
        <form method="post">
            <div class="form-row">
            <div class="form-group input-group mb-3 col-md-4">
            <input class="form-control" type="text" id="name" name="name" placeholder="Name" value={{project.name}} required/>
            </div>
            <div class="form-group input-group col-md-4">
            <input type='text' name="time" autocomplete="off" class="form-control" placeholder="Print time" id='time' value={{project.time}}>
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            <div class="form-group input-group col">
            <input class="form-control" type="text" id="weight" name="weight" placeholder="Weight" value={{project.weight}} required/>
            </div>
            <div class="form-group input-group">
            <input class="form-control" type="text" id="path" name="path" placeholder="Path of file" value={{project.path}} required/>
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary" href="{{url_for('projects.index')}}"> Cancel </a>
        </form>
    </section>
   <script type="text/javascript">
    var defaults = {
	calendarWeeks: true,
	showClear: true,
	showClose: true,
	allowInputToggle: true,
	useCurrent: false,
	ignoreReadonly: true,
	toolbarPlacement: 'top',
	icons: {
		time: 'fa fa-clock-o',
		date: 'fa fa-calendar',
		up: 'fa fa-angle-up',
		down: 'fa fa-angle-down',
		previous: 'fa fa-angle-left',
		next: 'fa fa-angle-right',
		today: 'fa fa-dot-circle-o',
		clear: 'fa fa-trash',
		close: 'fa fa-times'
        }
    };
    var optionsDatetime = $.extend({}, defaults, {format:'DD-MM-YYYY HH:mm'});
	var optionsDate = $.extend({}, defaults, {format:'DD-MM-YYYY'});
	var optionsTime = $.extend({}, defaults, {format:'HH:mm'});
    $(function () {
        $('#time').datetimepicker(optionsTime);
    });
    </script>
{% endblock %}

templates/projects/index.html
{% extends "base.html" %}
{% block  content%}
    <section>
        <div class="list-group list-group-flush mb-3">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Print Time</th>
                  <th scope="col">Weight</th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
           {% for project in projects | sort(attribute='path') | sort(attribute='name') %}
                <tr>
                  <th scope="row">{{ loop.index + pagination.skip }}</th>
                  <td>{{project.name}}</td>
                  <td>{{project.time}}</td>
                  <td>{{project.weight}}</td>
                  <td class="text-right">
                    <span><a title="edit" class="btn btn-primary btn-sm" href="{{url_for('projects.edit_project', project_id=project._id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
                    <span><a title="delete" data-id='{{project._id}}' class="btn btn-danger btn-sm conf-delete text-white"><i class="fa fa-trash" aria-hidden="true"></i></a></span>
                  </td>
                </tr>
            {% endfor %}
                </tbody>
            </table>
        </div>
        <a class="btn btn-success" href="{{url_for('projects.new_project')}}"> Create New </a>
        <span class="pull-right">{{ pagination.links }}</span>
    </section>

<script type="text/javascript">
 $(".conf-delete").click(function(){
    var id = $(this).data('id');
    bootbox.confirm("Are you sure?", function(result) {
      if(result)
          window.location = '/projects/delete/' + id;
    });
  });
</script>
{% endblock %}

templates/projects/new_project.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-project-form">
        <form id="new-project" action="/projects/new" method="post">
            <div class="form-row">
            <div class="form-group input-group mb-3 col-md-4">
            <input class="form-control" type="text" id="name" name="name" placeholder="Name" required/>
            </div>
            <div class="form-group input-group col-md-4">
            <input type='text' name="time" autocomplete="off" class="form-control" placeholder="Print time" id='time'>
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            <div class="form-group input-group col">
            <input class="form-control" type="text" id="weight" name="weight" placeholder="Weight" required/>
            </div>
            <div class="form-group input-group col">
            <input class="form-control" type="text" id="path" name="path" placeholder="Path of file" required/>
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary" href="{{url_for('projects.index')}}"> Cancel </a>
        </form>
    </section>
   <script type="text/javascript">
    var defaults = {
	calendarWeeks: true,
	showClear: true,
	showClose: true,
	allowInputToggle: true,
	useCurrent: false,
	ignoreReadonly: true,
	toolbarPlacement: 'top',
	icons: {
		time: 'fa fa-clock-o',
		date: 'fa fa-calendar',
		up: 'fa fa-angle-up',
		down: 'fa fa-angle-down',
		previous: 'fa fa-angle-left',
		next: 'fa fa-angle-right',
		today: 'fa fa-dot-circle-o',
		clear: 'fa fa-trash',
		close: 'fa fa-times'
        }
    };
    var optionsDatetime = $.extend({}, defaults, {format:'DD-MM-YYYY HH:mm'});
	var optionsDate = $.extend({}, defaults, {format:'DD-MM-YYYY'});
	var optionsTime = $.extend({}, defaults, {format:'HH:mm'});
    $(function () {
        $('#time').datetimepicker(optionsTime);
    });
    </script>
{% endblock %}