models/shift.py
import datetime
import uuid
from typing import Dict

from common.Database import Database


class Shift:
    collection = "shifts"

    def __init__(self, desc: str, timein: datetime, timeout: datetime, _id: str = None):
        self.desc = desc
        self.timein = timein
        self.timeout = timeout
        self.collection = "shifts"
        self._id = _id or uuid.uuid4().hex

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "desc": self.desc,
            "timein": self.timein,
            "timeout": self.timeout
        }

    def save_to_mongo(self):
        Database.update(self.collection, {"_id": self._id}, self.json())

    def remove_from_mongo(self):
        Database.remove(self.collection, {"_id": self._id})

    @classmethod
    def find_one_by(cls, attribute, value):
        result = Database.find_one(cls.collection, {attribute: value})
        return cls(**result) if result else None

    @classmethod
    def find_many_by(cls, attribute, value):
        result = Database.find(cls.collection, {attribute: value})
        return [cls(**elem) for elem in result] if result else None

    @classmethod
    def get_by_id(cls, _id):
        return cls.find_one_by("_id", _id)

    @classmethod
    def all(cls, skip=0, limit=0):
        result = Database.find("shifts", {}).sort("desc").skip(skip).limit(limit)
        return [cls(**shift) for shift in result] if result else None

    @classmethod
    def get_by_search(cls, parameter):
        result = Database.DATABASE[cls.collection].find(
            {"$or":
                [
                    {"desc": {"$regex": parameter, "$options": 'i'}}
                ]
            })
        return [cls(**elem) for elem in result] if result else None

views/shifts.py
from flask import Blueprint, request, render_template, make_response, redirect, url_for, flash, Markup
from flask_paginate import Pagination, get_page_parameter
from models.shift import Shift
from models.user.decorators import requires_login, requires_admin

shift_blueprints = Blueprint("shifts", __name__)

view = {
            "title": "Shifts",
            "icon": "fa-clock-o",
            "name": "shifts",
            "nav_on": True,
            "search_on": False
        }


@shift_blueprints.route('/')
@requires_login
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)

    per_page = 6
    offset = (page - 1) * per_page

    shifts = Shift.all(offset, per_page)
    counter = len(Shift.all())

    view['title'] = "Shifts"
    view['search_on'] = True

    search = False
    q = request.args.get('q')
    if q:
        search = True

    pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                            search=search, record_name='shifts')

    return render_template('shifts/index.html', shifts=shifts, pagination=pagination, view=view)


@shift_blueprints.route('/new', methods=['GET', 'POST'])
@requires_login
def new_shift():
    if request.method == 'POST':
        desc = request.form['desc']
        timein = request.form['timein']
        timeout = request.form['timeout']

        if Shift.find_one_by("desc", desc):
            message = Markup('<i class="fa fa-warning"></i> Error: The shift you are trying to create already exist.')
            flash(message, 'warning')
            view['title'] = "New Shift"
            view['search_on'] = False
            return render_template('shifts/new_shift.html', view=view)
        else:
            Shift(desc, timein, timeout).save_to_mongo()
            flash('The printer was successfully created!', 'success')
            return redirect(url_for('shifts.index'))
    else:
        view['title'] = "New shift"
        view['search_on'] = False
        return render_template('shifts/new_shift.html', view=view)


@shift_blueprints.route('/edit/<string:shift_id>', methods=['GET', 'POST'])
@requires_login
def edit_shift(shift_id):
    shift = Shift.get_by_id(shift_id)

    if request.method == 'POST':
        shift.desc = request.form['desc']
        shift.timein = request.form['timein']
        shift.timeout = request.form['timeout']

        x_shift = Shift.find_one_by("desc", shift.desc)
        if x_shift is not None:
            if x_shift._id != shift_id:
                message = Markup('<i class="fa fa-warning"></i> Error: The shift cannot be created, already exist.')
                flash(message, 'warning')
                view['title'] = "Edit shift"
                view['search_on'] = False
                return render_template('shifts/edit_shift.html', shift=shift, view=view)

        shift.save_to_mongo()
        flash('The shift was updated!', 'success')
        return redirect(url_for('shifts.index'))
    else:
        view['title'] = "Edit shift"
        view['search_on'] = False
        return render_template('shifts/edit_shift.html', shift=shift, view=view)


@shift_blueprints.route('/delete/<string:shift_id>', methods=['GET'])
@requires_login
@requires_admin
def remove_shift(shift_id):
    shift = Shift.get_by_id(shift_id)
    shift.remove_from_mongo()
    flash('The shift was deleted!', 'danger')
    return redirect(url_for('shifts.index'))


@shift_blueprints.route('/search', methods=['POST'])
@requires_login
def search():
    if request.method == 'POST' and request.form['parameter'] != "":
        parameter = request.form['parameter']
        shifts = Shift.get_by_search(parameter)

        page = request.args.get(get_page_parameter(), type=int, default=1)
        counter = len(shifts)
        per_page = counter if counter > 0 else 1
        offset = counter

        view['title'] = "Shifts"
        view['search_on'] = True

        search = False
        q = request.args.get('q')
        if q:
            search = True

        pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                                search=search, record_name='shifts')

        return render_template('shifts/index.html', shifts=shifts, pagination=pagination, view=view)
    else:
        return redirect(url_for('shifts.index'))

templates/shifts/edit_shift.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-shift-form">
        <form method="post">
             <div class="form-row">
            <div class="form-group input-group col-md-10">
            <input class="form-control" type="text" id="desc" name="desc" placeholder="Description" value={{shift.desc}} required/>
            </div>
           <div class="form-group input-group col-md-5">
            <input type='text' name="timein" class="form-control" autocomplete="off" placeholder="Time IN" id='timein' value={{shift.timein}} required/>
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            <div class="form-group input-group col-md-5">
            <input type='text' name="timeout" class="form-control" autocomplete="off" placeholder="Time OUT" id='timeout' value={{shift.timeout}} required/>
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-secondary" href="{{url_for('shifts.index')}}"> Cancel </a>
        </form>
    </section>
<script type="text/javascript">
    var defaults = {
	calendarWeeks: true,
	showClear: true,
	showClose: true,
	allowInputToggle: true,
	useCurrent: false,
	ignoreReadonly: true,
	toolbarPlacement: 'top',
	icons: {
		time: 'fa fa-clock-o',
		date: 'fa fa-calendar',
		up: 'fa fa-angle-up',
		down: 'fa fa-angle-down',
		previous: 'fa fa-angle-left',
		next: 'fa fa-angle-right',
		today: 'fa fa-dot-circle-o',
		clear: 'fa fa-trash',
		close: 'fa fa-times'
        }
    };
    var optionsDate = $.extend({}, defaults, {format:'DD-MM-YYYY'});
	var optionsTime = $.extend({}, defaults, {format:'HH:mm'});
    $(function () {
        $('#timein').datetimepicker(optionsTime);
        $('#timeout').datetimepicker(optionsTime);
    });
    </script>
{% endblock %}

templates/shifts/index.html
{% extends "base.html" %}
{% block  content%}
    <section>
        <div class="list-group list-group-flush mb-3">
           {% for shift in shifts | sort(attribute='timein') %}
            <div class="list-group-item">
                <span>{{shift.desc}} | </span>
                <span>Horario: {{shift.timein}} - {{shift.timeout}}</span>
                <div id="options" class="float-right">
                <span><a title="edit" class="btn btn-primary btn-sm" href="{{url_for('shifts.edit_shift', shift_id=shift._id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
                <span><a title="delete" data-id='{{shift._id}}' class="btn btn-danger btn-sm conf-delete text-white"><i class="fa fa-trash" aria-hidden="true"></i></a></span>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-success" href="{{url_for('shifts.new_shift')}}"> Create New </a>
        <span class="pull-right">{{ pagination.links }}</span>
    </section>

<script type="text/javascript">
 $(".conf-delete").click(function(){
    var id = $(this).data('id');
    bootbox.confirm("Are you sure?", function(result) {
      if(result)
          window.location = '/shifts/delete/' + id;
    });
  });
</script>
{% endblock %}

templates/shifts/new_shift.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-shift-form">
        <form id="new-shift" action="/shifts/new" method="post">
             <div class="form-row">
            <div class="form-group input-group col-md-10">
            <input class="form-control" type="text" id="desc" name="desc" placeholder="Description" required />
            </div>
           <div class="form-group input-group col-md-5">
            <input type='text' name="timein" autocomplete="off" class="form-control" placeholder="Time IN" id='timein' required />
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            <div class="form-group input-group col-md-5">
            <input type='text' name="timeout" autocomplete="off" class="form-control" placeholder="Time OUT" id='timeout' required />
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-clock-o"></span>
                </span>
            </div>
            </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary" href="{{url_for('shifts.index')}}"> Cancel </a>
        </form>
    </section>
     <script type="text/javascript">
    var defaults = {
	calendarWeeks: true,
	showClear: true,
	showClose: true,
	allowInputToggle: true,
	useCurrent: false,
	ignoreReadonly: true,
	toolbarPlacement: 'top',
	icons: {
		time: 'fa fa-clock-o',
		date: 'fa fa-calendar',
		up: 'fa fa-angle-up',
		down: 'fa fa-angle-down',
		previous: 'fa fa-angle-left',
		next: 'fa fa-angle-right',
		today: 'fa fa-dot-circle-o',
		clear: 'fa fa-trash',
		close: 'fa fa-times'
        }
    };
    var optionsDate = $.extend({}, defaults, {format:'DD-MM-YYYY'});
	var optionsTime = $.extend({}, defaults, {format:'HH:mm'});
    $(function () {
        $('#timein').datetimepicker(optionsTime);
        $('#timeout').datetimepicker(optionsTime);
    });
    </script>
{% endblock %}