models/printer.py
import uuid
from typing import Dict


from octorest import OctoRest
from common.Database import Database
import json
import datetime
import time
import concurrent.futures
import socket
from urllib.parse import urlparse


class Printer:
    collection = "printers"

    def __init__(self, name: str, url: str, apikey: str, server: bool = None, _id: str = None):
        self.server = server
        self.name = name
        self.url = url
        self.apikey = apikey
        self.collection = "printers"
        self._id = _id or uuid.uuid4().hex

    def json(self) -> Dict:
        return {
            "_id": self._id,
            "name": self.name,
            "url": self.url,
            "apikey": self.apikey,
            "server": self.server
        }

    def save_to_mongo(self):
        Database.update(self.collection, {"_id": self._id}, self.json())

    def remove_from_mongo(self):
        Database.remove(self.collection, {"_id": self._id})

    def check_socket(self):
        parse_url = urlparse(self.url)
        hostname = parse_url.hostname
        if parse_url.port is None:
            if parse_url.scheme == 'https':
                port = 443
            else:
                port = 80
        else:
            port = parse_url.port
        try:
            sock = socket.create_connection((hostname, port), timeout=2)
        except:
            return False
        else:
            return True

    def con(self):
        if self.check_socket():
            try:
                con = OctoRest(url=self.url, apikey=self.apikey)
            except Exception as e:
                return False
            else:
                return con
        else:
            return False

    def state(self):
        if isinstance(self.con(), bool):
            return False
        else:
            try:
                state = self.con().connection_info()['current']['state']
                error204 = "204 No Content"
                error400 = "400 Bad Request"
                error409 = "Error"
                error_closed = "Closed"
                if error_closed not in state and error204 not in state and error400 not in state and error409 not in state:
                    return True
            except Exception as e:
                return False

    def connect(self):
        if not self.state():
            try:
                con = self.con()
            except Exception as e:
                raise TypeError(e)
            else:
                con.connect()
                return True

    def start_job(self) -> bool:

        if self.get_flag_operational() or self.get_flag_ready():
            if self.con().start():
                return True

        if self.get_flag_paused():
            if self.con().resume():
                return True

        return False

    def pause_job(self) -> bool:
        if self.get_flag_printing():
            if self.con().pause():
                return True
        return False

    def stop_job(self) -> bool:
        if self.get_flag_printing() or self.get_flag_paused():
            if self.con().cancel():
                return True
        return False

    def get_parameters(self):
        if self.state():
            parameters = self.con().printer()
            return parameters
        else:
            return False

    def get_job_info(self):
        if self.state():
            job_info = self.con().job_info()
            return job_info
        else:
            return False

    def get_flag_cancelling(self):
        if self.get_parameters():
            if 'Cancelling' in self.get_parameters()['state']['text']:
                return True
        return False

    def get_flag_operational(self):
        if self.get_parameters():
            if 'Operational' in self.get_parameters()['state']['text']:
                return True
        return False

    def get_flag_paused(self):
        if self.get_parameters():
            if 'Paused' in self.get_parameters()['state']['text']:
                return True
        return False

    def get_flag_pausing(self):
        if self.get_parameters():
            if 'Pausing' in self.get_parameters()['state']['text']:
                return True
        return False

    def get_flag_printing(self):
        if self.get_parameters():
            if 'Printing' in self.get_parameters()['state']['text']:
                return True
        return False

    def get_flag_ready(self):
        if self.get_parameters():
            if 'Ready' in self.get_parameters()['state']['text']:
                return True
        return False

    @staticmethod
    def do_history(printer_id):
        self = Printer.get_by_id(printer_id)
        history = {
            "printer_id": self._id,
            "printer_name": self.name,
            "state": "inactive",
            "cor": "danger",
            "temperature": {
                "tool": 0,
                "bed": 0
            },
            "target": {
                "tool": 0,
                "bed": 0
            },
            "job": {
                "file_name": None,
                "estimatedPrintTime": 0,
                "lastPrintTime": 0,
                "filament_length": 0,
                "completion": '0%',
                "printTime": 0,
                "printTimeLeft": 0,
                "left_time": 0,
            }
        }

        parameters = self.get_parameters()
        if not isinstance(parameters, bool):

            # flags = parameters['state']['flags'] if 'flags' in parameters['state'] else False
            history['state'] = parameters['state']['text'] if 'text' in parameters['state'] else "inactive"

            if history['state'] == "Operational" or history['state'] == "Ready":
                history['cor'] = "success"
            if history['state'] == "Printing":
                history['cor'] = "primary"
            if history['state'] == "Pausing" or history['state'] == "Paused" or history['state'] == "Cancelling":
                history['cor'] = "warning"

            temps = parameters['temperature'] if 'temperature' in parameters else False
            if temps is not False:
                history['temperature']['tool'] = self.get_tool_temperature(temps) if self.get_tool_temperature(
                    temps) else 0
                history['temperature']['bed'] = self.get_bed_temperature(temps) if self.get_bed_temperature(
                    temps) else 0
                history['target']['tool'] = self.get_tool_target(temps) if self.get_tool_target(temps) else 0
                history['target']['bed'] = self.get_bed_target(temps) if self.get_bed_target(temps) else 0

            job_info = self.get_job_info()

            job = job_info['job'] if 'job' in job_info else False
            if job is not False:
                estimatedPrintTime = job['estimatedPrintTime'] if 'estimatedPrintTime' in job else 0
                history['job']['estimatedPrintTime'] = str(datetime.timedelta(seconds=estimatedPrintTime)).split('.')[
                    0] if estimatedPrintTime is not None else "00:00:00"
                # history['job']['filament_length'] = 0

            file = job_info['job']['file'] if 'file' in job_info['job'] else False
            if file is not False:
                history['job']['file_name'] = str(file['name']).split('.')[0] if file['name'] is not None else "Unknown"

            progress = job_info['progress'] if 'progress' in job_info else False
            if progress is not False:
                completion = progress['completion'] if 'completion' in progress else 0
                if completion is not None:
                    history['job']['completion'] = str(completion).split('.')[0] + "%"
                printtimeleft = progress['printTimeLeft'] if 'printTimeLeft' in progress else 0
                if printtimeleft is not None:
                    history['job']['left_time'] = printtimeleft

                printTime = progress['printTime'] if 'printTime' in progress else 0
                history['job']['printTime'] = str(datetime.timedelta(seconds=printTime)).split('.')[
                    0] if printTime is not None else "00:00:00"

                PrintTimeLeft = progress['printTimeLeft'] if 'printTimeLeft' in progress else 0
                history['job']['printTimeLeft'] = str(datetime.timedelta(seconds=PrintTimeLeft)).split('.')[
                    0] if PrintTimeLeft is not None else "00:00:00"

            last_job = job_info['lastPrintTime'] if 'lastPrintTime' in job_info else False
            if last_job is not False:
                history['job']['lastPrintTime'] = str(datetime.timedelta(seconds=last_job)).split('.')[
                    0] if last_job is not None else "00:00:00"

        return history

    @staticmethod
    def history_threads():
        history = []
        ptime = 0
        printers = Printer.all()

        with concurrent.futures.ThreadPoolExecutor(16) as executor:
            future = [executor.submit(Printer.do_history, printer._id) for printer in printers]

            for f in concurrent.futures.as_completed(future, timeout=60):
                result = f.result()
                if result['job']['left_time'] > ptime:
                    ptime = result['job']['left_time']

                history.append(result)

        left_time = ptime * 1000
        return history, left_time

    @classmethod
    def find_one_by(cls, attribute, value):
        result = Database.find_one(cls.collection, {attribute: value})
        return cls(**result) if result else None

    @classmethod
    def find_many_by(cls, attribute, value):
        result = Database.find(cls.collection, {attribute: value})
        return [cls(**elem) for elem in result] if result else None

    @classmethod
    def get_by_id(cls, _id):
        return cls.find_one_by("_id", _id)

    @classmethod
    def all(cls, skip=0, limit=0):

views/printers.py
from flask import Blueprint, request, render_template, make_response, redirect, jsonify, url_for, flash, Markup
from flask_paginate import Pagination, get_page_parameter
from models.printer import Printer
from models.user.decorators import requires_login, requires_admin

printer_blueprints = Blueprint("printers", __name__)

view = {
    "title": "Printers",
    "icon": "fa-print",
    "name": "printers",
    "nav_on": True,
    "search_on": False
}


@printer_blueprints.route('/')
@requires_login
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)

    per_page = 6
    offset = (page - 1) * per_page

    printers = Printer.all(offset, per_page)
    counter = len(Printer.all())

    view['title'] = "Printers"
    view['search_on'] = True

    search = False
    q = request.args.get('q')
    if q:
        search = True

    pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                            search=search, record_name='printers')

    return render_template('printers/index.html', printers=printers, pagination=pagination, view=view)


@printer_blueprints.route('/new', methods=['GET', 'POST'])
@requires_login
def new_printer():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        apikey = request.form['apikey']
        server = True if 'server' in request.form else False

        if Printer.find_one_by("name", name) or Printer.find_one_by("url", url):
            message = Markup(
                '<i class="fa fa-warning"></i> Error: The printer/url you are trying to create already exist.')
            flash(message, 'warning')
            view['title'] = "New Printer"
            view['search_on'] = False
            return render_template('printers/new_printer.html', view=view)
        else:
            Printer(name, url, apikey, server).save_to_mongo()
            flash('The printer was successfully created!', 'success')
            return redirect(url_for('printers.index'))
    else:
        view['title'] = "New printer"
        view['search_on'] = False
        return render_template('printers/new_printer.html', view=view)


@printer_blueprints.route('/edit/<string:printer_id>', methods=['GET', 'POST'])
@requires_login
def edit_printer(printer_id):
    printer = Printer.get_by_id(printer_id)

    if request.method == 'POST':
        printer.name = request.form['name']
        printer.url = request.form['url']
        printer.apikey = request.form['apikey']
        printer.server = True if 'server' in request.form else False

        x_printer = Printer.find_one_by("url", printer.url)
        if x_printer is not None:
            if x_printer._id != printer_id:
                message = Markup('<i class="fa fa-warning"></i> Error: The printer cannot be created, already exist.')
                flash(message, 'warning')
                view['title'] = "Edit printer"
                view['search_on'] = False
                return render_template('printers/edit_printer.html', printer=printer, view=view)

        printer.save_to_mongo()
        flash('The printer was updated!', 'success')
        return redirect(url_for('printers.index'))
    else:
        view['title'] = "Edit printer"
        view['search_on'] = False
        return render_template('printers/edit_printer.html', printer=printer, view=view)


@printer_blueprints.route('/delete/<string:printer_id>', methods=['GET'])
@requires_login
@requires_admin
def remove_printer(printer_id):
    printer = Printer.get_by_id(printer_id)
    printer.remove_from_mongo()
    flash('The printer was deleted!', 'danger')
    return redirect(url_for('printers.index'))


@printer_blueprints.route('/search', methods=['POST'])
@requires_login
def search():
    if request.method == 'POST' and request.form['parameter'] != "":
        parameter = request.form['parameter']
        printers = Printer.get_by_search(parameter)

        page = request.args.get(get_page_parameter(), type=int, default=1)
        counter = len(printers)
        per_page = counter if counter > 0 else 1
        offset = counter

        view['title'] = "Printers"
        view['search_on'] = True

        search = False
        q = request.args.get('q')
        if q:
            search = True

        pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                                search=search, record_name='printers')

        return render_template('printers/index.html', printers=printers, pagination=pagination, view=view)
    else:
        return redirect(url_for('printers.index'))


@printer_blueprints.route('/dashboard', methods=['GET'])
@requires_login
def dashboard():
    view['title'] = "Dashboard"
    view["icon"] = "fa-dashboard"
    view['search_on'] = False

    return render_template('printers/dashboard.html', view=view)


@printer_blueprints.route('/dashboard_update', methods=['GET'])
@requires_login
def dashboard_update():
    history, left_time = Printer.history_threads()
    result = render_template('printers/thread_dashboard.html', history=history, left_time=left_time)
    return jsonify(result=result)


@printer_blueprints.route('/start/printer_id=<string:printer_id>', methods=['GET'])
@requires_login
def start(printer_id):
    printer = Printer.get_by_id(printer_id)
    if printer.start_job():
        return jsonify(result=True)

    return jsonify(result=False)


@printer_blueprints.route('/pause/printer_id=<string:printer_id>', methods=['GET'])
@requires_login
def pause(printer_id):
    printer = Printer.get_by_id(printer_id)
    if printer.pause_job():
        return jsonify(result=True)

    return jsonify(result=False)


@printer_blueprints.route('/stop/printer_id=<string:printer_id>', methods=['GET'])
@requires_login
def stop(printer_id):
    printer = Printer.get_by_id(printer_id)
    if printer.stop_job():
        return jsonify(result=True)

    return jsonify(result=False)


@printer_blueprints.route('/connect/printer_id=<string:printer_id>', methods=['GET'])
@requires_login
def connect(printer_id):
    printer = Printer.find_one_by("_id", printer_id)
    if printer.connect():
        return jsonify(result=True)

    return jsonify(result=False)

templates/printers/dashboard.html
{% extends "base.html" %}
{% block  content%}
<link href="{{ url_for('static', filename='css/progressbar_tool.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/progressbar_bed.css') }}" rel="stylesheet">

<section id="render_dashboard">
    <div class="h-100 d-flex justify-content-center align-items-center m-0 p-0" style="filter: grayscale(100%); -webkit-filter: grayscale(100%);">
        <img src="{{ url_for('static', filename='images/loading.webp') }}" width="25%" />
    </div>
    <div class="h-100 d-flex justify-content-center align-items-center m-0 p-0"><span >Loading...</span></div>
    <div class="h-100 d-flex justify-content-center align-items-center m-0 p-0"><span >Please wait, this may take a while!</span></div>
</section>

<script type="text/javascript">
function load(){
    var msj = document.getElementById("msj_loading");
    // don't cache ajax or content won't be fresh
    $.ajax({
        cache: false,
        type: 'get',
        dataType: 'json',
        headers: { "cache-control": "no-cache" },
        url: '/printers/dashboard_update',

        success: function (data) {
            $("#render_dashboard").html(data.result);
            if (msj !== null){
                msj.innerHTML = "";
            }
        },

        complete: function() {
            // Schedule the next request when the current one's complete
            setTimeout(load, 3000);
        }
    });
// end
}

$(load());

</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>

{% endblock %}

templates/printers/edit_printer.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-printer-form">
        <form method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control" type="text" id="name" name="name" value="{{ printer.name }}" required/>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input class="form-control" type="text" id="url" name="url"  value="{{ printer.url }}" required/>
            </div>
            <div class="form-group">
                <label for="apikey">ApiKey</label>
                <input class="form-control" type="text" id="apikey" name="apikey" value="{{ printer.apikey }}" required/>
            </div>
            <div class="form-group">
                <label for="server">Printer Type: </label>
                {% if printer.server%}
                    <input id="server" class="form-control" checked type="checkbox" data-toggle="toggle" data-on="Server" data-off="Client" name="server" data-offstyle="success" data-onstyle="danger"/>
                {% else %}
                    <input id="server" class="form-control" type="checkbox" data-toggle="toggle" data-on="Server" data-off="Client" name="server" data-offstyle="success" data-onstyle="danger"/>
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-secondary" href="{{url_for('printers.index')}}"> Cancel </a>
        </form>
    </section>
{% endblock %}

templates/printers/index.html
{% extends "base.html" %}
{% block  content%}
    <section>
        <div class="list-group list-group-flush mb-3">
           {% for printer in printers | sort(attribute='name') %}
            <div class="list-group-item">
                <span class="pr-2 border-right">{{printer.name}}</span>
                <span class="pr-2 border-right"><a href="{{printer.url}}">{{printer.url}}</a></span>
                <span>APIKEY: {{printer.apikey}}</span>
                {% if printer.server %}
                    <span class="pl-2 border-left text-success">SERVER <i class="fa fa-check" aria-hidden="true"></i></span>
                {% endif %}
                <div id="options" class="float-right">
                <span><a title="edit" class="btn btn-primary btn-sm" href="{{url_for('printers.edit_printer', printer_id=printer._id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
                <span><a title="delete" data-id='{{printer._id}}' class="btn btn-danger btn-sm conf-delete text-white"><i class="fa fa-trash" aria-hidden="true"></i></a></span>
                </div>

            </div>
            {% endfor %}
        </div>
        <a class="btn btn-success" href="{{url_for('printers.new_printer')}}"> Create New </a>
        <span class="pull-right">{{ pagination.links }}</span>
    </section>

<script type="text/javascript">
 $(".conf-delete").click(function(){
    var id = $(this).data('id');
    bootbox.confirm("Are you sure?", function(result) {
      if(result)
          window.location = '/printers/delete/' + id;
    });
  });
</script>
{% endblock %}

templates/printers/new_printer.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-printer-form">
        <form id="new-printer" action="/printers/new" method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input class="form-control" type="text" id="name" name="name" required/>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input class="form-control" type="text" id="url" placeholder="http://..." name="url" required/>
            </div>
            <div class="form-group">
                <label for="apikey">ApiKey</label>
                <input class="form-control" type="text" id="apikey" name="apikey" required/>
            </div>
            <div class="form-group">
                <label for="server">Printer Type: </label>
                <input id="server" class="form-control" type="checkbox" data-toggle="toggle" data-on="Server" data-off="Client" name="server" data-offstyle="success" data-onstyle="danger" value="False" />
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-secondary" href="{{url_for('printers.index')}}"> Cancel </a>
        </form>
    </section>
{% endblock %}

templates/printers/partial_dashboard.html
<h5 class="text-center"><i class="fa fa-2x fa-clock-o align-middle pr-2"></i><span id="left_time"><span id="timer"></span><span>left to end the shift.</span></span></h5>
<div class="text-center"><span id="msj_loading"></span></div>
   <hr>
   <div class="row" id="pr-dashboard">
     {% set count = namespace(value=0) %}
     {% for printer in printers %}
       {% set history = printer.get_history() %}
       <div class="col-sm-3">
        <div class="card mb-2" style="width: 250px">
          <div class="card-header p-0 m-0 dashboard-card-{{ history['cor'] }}" id='heading{{ printer._id }}' style="cursor: pointer" aria-hidden="true" data-toggle="collapse" data-target='#collapse{{ printer._id }}' aria-expanded="false" aria-controls='collapse{{ printer._id }}'>
              <img class="p-1 mr-3 float-left text-white ml-1 mt-1" src="{{ static('images/icon_3dprinter.png') }}" height="48px" />
              <span class="pull-left m-1">
                  <span>{{printer.name}}</span>
                  <br/>
                  status: {{ history['state'] }}
              </span>
              <p style="border-radius: 2px;" class="pull-right p-2 pt-3 pb-3 mb-0"><i class="fa fa-chevron-down text-secondary"></i></p>
          </div>

          {% if history['state'] == "inactive"%}
              <div id='collapse{{ printer._id }}' class="collapse multi-collapse" aria-labelledby='heading{{ printer._id }}'>
                  <div class="card-body alert-secondary p-2" style="height: 240px">
                    <section class="h-100 d-flex justify-content-center align-items-center">
                        <a class="btn btn-light p-2 pl-3 pr-3 option" data-option="connect" data-printer="{{printer._id}}">CONNECT</a>
                    </section>
                  </div>
                  <div class="card-footer p-1 pl-2 pr-2" style="height: 32px"></div>
             </div>
           {% else %}
             {% set i = ( i | default(0) ) + 1 %}
             <div id='collapse{{ printer._id }}' class="collapse multi-collapse" aria-labelledby='heading{{ printer._id }}'>
                  <div class="card-body text-dark p-2" style="height: 240px">
                    <section class="card-title row" style="height:30px!important; overflow:hidden!important;">
                      <div class="text-left col-md-7 m-0">
                        <h6 style="font-size:14px; height: 24px!important; overflow: hidden" class="p-0 pt-1">
                            <span class="align-middle"> {{ history['job']['file_name'] }} </span>
                        </h6>
                      </div>
                      <div class="text-right col-md-5 pl-1 m-0">
                        <span><a title="start" class="btn btn-success btn-sm text-white option" data-option="start" data-printer="{{printer._id}}" style="padding: 2px 6px !important;"><i class="fa fa-play" aria-hidden="true"></i></a></span>
                        <span><a title="pause" class="btn btn-warning btn-sm text-white option" data-option="pause" data-printer="{{printer._id}}" style="padding: 2px 6px !important;"><i class="fa fa-pause" aria-hidden="true"></i></a></span>
                        <span><a title="stop" class="btn btn-danger btn-sm text-white option" data-option="stop" data-printer="{{printer._id}}" style="padding: 2px 6px !important;"><i class="fa fa-stop" aria-hidden="true"></i></a></span>
                      </div>
                    </section>
                    <section class="card-text p-5" style="height:100px!important; overflow:hidden!important;">
                        <!--- Gcode viewer -->
                    </section>
                    <section class="card-text d-flex align-items-end">
                      <div class="col-md-6">
                            <div class="cs-widget">
                              <div class="cs-progress-container">
                                <div class="cs-progress-bar-tool tool" id="tool{{ count.value }}" data-temp="{{ history['temperature']['tool'] }}" data-max="320">
                                  <div class="cs-points">tool</div>
                                </div>
                               </div>
                             </div>
                        </div>
                        <div class="col-md-6">
                            <div class="cs-widget">
                              <div class="cs-progress-container">
                                <div class="cs-progress-bar-bed bed" id="bed{{ count.value }}" data-temp="{{ history['temperature']['bed'] }}" data-max="150">
                                  <div class="cs-points">bed</div>
                                </div>
                              </div>
                            </div>
                        </div>
                    </section>
                  </div>
                  <div class="card-footer text-white bg-{{ history['cor'] }} p-1 pl-2 pr-2" style="height: 32px">
                        <h5>
                            <span class="pull-left">{{ history['job']['printTimeLeft'] }}</span>
                            <span class="pull-right">{{ history['job']['completion'] }}</span>
                        </h5>
                  </div>
             </div>
            {% set count.value = count.value + 1 %}
           {% endif %}
        </div>
       </div>
     {% endfor %}
   </div>

<script src="{{ url_for('static', filename='js/progressbar_tool.js') }}"></script>
<script src="{{ url_for('static', filename='js/progressbar_bed.js') }}"></script>

<script type="text/javascript">

var left_time = {{ left_time }};
var countDownDate = left_time + new Date().getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

   if (hours   < 10) {hours   = "0"+hours;}
   if (minutes < 10) {minutes = "0"+minutes;}
   if (seconds < 10) {seconds = "0"+seconds;}

  // Output the result in an element with id="timer"
  if (days > 0){
    document.getElementById("timer").innerHTML = days + " days " + hours + ":" + minutes + ":" + seconds + "h ";
  } else {
    document.getElementById("timer").innerHTML = hours + ":" + minutes + ":" + seconds + "h ";
  }

  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("left_time").innerHTML = "Shift Ended";
  }
}, 1000);

$(function options() {

  $(".option").click(function () {
      var printer = $(this).data('printer');
      var option = $(this).data('option');
    $.ajax({
      type: 'get',
      dataType: 'json',
      cache: false,
      headers: { "cache-control": "no-cache" },
      url: '/printers/'+ option +'/printer_id=' + printer,
      success: function (data) {
            setTimeout(load, 2000);
        }
    });
  });

});

</script>