views/jobs.py
from datetime import datetime
from flask import Blueprint, request, render_template, make_response, redirect, url_for, jsonify, flash, Markup
from flask_paginate import Pagination, get_page_parameter
import pdfkit

from models.filament import Filament
from models.job import Job
from models.printer import Printer
from models.project import Project
from models.shift import Shift
from models.user.decorators import requires_login, requires_admin
import time

job_blueprints = Blueprint("jobs", __name__)

view = {
        "title": "Job List",
        "icon": "fa-archive",
        "name": "jobs",
        "nav_on": True,
        "search_on": False
    }


@job_blueprints.route('/', methods=['GET'])
@requires_login
def index():

    counter = Job.jobs_amount()
    jobs = Job.all()

    page = request.args.get(get_page_parameter(), type=int, default=1)

    per_page = 8
    offset = 4 * page
    start = (page - 1) * 4

    search = False
    q = request.args.get('q')
    if q:
        search = True

    view['title'] = "Jobs"
    view['search_on'] = True

    pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                            search=search, record_name='jobs')

    return render_template('jobs/index.html', jobs=jobs, now=datetime.today().strftime('%Y-%m-%d'),
                           pagination=pagination, offset=offset, start=start, view=view)


@job_blueprints.route('/new', methods=['GET', 'POST'])
@requires_login
def new_job():
    if request.method == 'POST':
        orders = request.form.getlist('order_id[]')
        printers = request.form.getlist('printer_id[]')
        projects = request.form.getlist('project_id[]')
        filaments = request.form.getlist('filament_id[]')
        list_obs = request.form.getlist('obs[]')
        date = request.form['date']
        shift_id = request.form['shift_id']
        for count in range(len(printers)):
            order_id = orders[count]
            printer_id = printers[count]
            project_id = projects[count]
            filament_id = filaments[count]
            obs = list_obs[count]
            status = True
            job = Job(date, order_id, shift_id, printer_id, project_id, filament_id, obs, status)
            if not job.job_exist():
                job.save_to_mongo()

        for printer in Printer.all():
            order_id = ""
            printer_id = printer._id
            project_id = None
            filament_id = None
            obs = ""
            status = False
            job = Job(date, order_id, shift_id, printer_id, project_id, filament_id, obs, status)
            if not job.job_exist():
                job.save_to_mongo()

        flash('The job was created!', 'success')
        return redirect(url_for('jobs.index'))
    else:

        view['title'] = "New jobs"
        view['search_on'] = False

        shifts = Shift.all()
        printers = Printer.all()
        projects = Project.all()
        filaments = Filament.all()
        latest_jobs = Job.get_latest_jobs()
        return render_template('jobs/new_job.html', shifts=shifts, printers=printers, projects=projects,
                               filaments=filaments, latest_jobs=latest_jobs, view=view)


@job_blueprints.route('/edit/<string:job_id>', methods=['GET', 'POST'])
@requires_login
def edit_job(job_id):
    job = Job.get_by_id(job_id)
    filaments = Filament.all()
    projects = Project.all()

    if request.method == 'POST':
        job.order_id = request.form['order_id'] if 'order_id' in request.form else ""
        job.project_id = request.form['project_id'] if 'project_id' in request.form else None
        job.filament_id = request.form['filament_id'] if 'filament_id' in request.form else None
        job.obs = request.form['obs'] if 'obs' in request.form else ""
        job.status = True if 'project_id' in request.form else False
        job.save_to_mongo()
        flash('The job was updated!', 'success')
        return redirect(url_for('jobs.index'))

    else:
        view['title'] = "Edit jobs"
        view['search_on'] = False
        return render_template('jobs/edit_job.html', job=job, filaments=filaments, projects=projects, view=view)


@job_blueprints.route('/delete/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def remove_job(date, shift_id):
    jobs = Job.find_many_by_date_shift(date, shift_id)
    for job in jobs:
        job.remove_from_mongo()
    flash('The job was deleted!', 'danger')
    return redirect(url_for('jobs.index'))


@job_blueprints.route('/search', methods=['POST'])
@requires_login
def search():
    if request.method == 'POST' and request.form['parameter'] != "":
        parameter = request.form['parameter']
        jobs = Job.get_by_search(parameter)

        counter = Job.search_amount(parameter)

        page = request.args.get(get_page_parameter(), type=int, default=1)

        per_page = counter if counter > 0 else 1
        offset = counter
        start = 0

        view['title'] = "Edit jobs"
        view['search_on'] = True

        search = False
        q = request.args.get('q')
        if q:
            search = True

        pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                                search=search, record_name='jobs')

        return render_template('jobs/index.html', jobs=jobs, now=datetime.today().strftime('%Y-%m-%d'),
                               pagination=pagination, offset=offset, start=start, view=view)
    else:
        return redirect(url_for('jobs.index'))


@job_blueprints.route('/heat/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def heat_printers(date, shift_id):
    jobs = Job.find_many_by_date_shift(date, shift_id)
    for job in jobs:
        if job.status is True:
            Printer.heat(job.printer_id)
    return redirect(url_for('jobs.index'))


@job_blueprints.route('/start/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def start_jobs(date, shift_id):
    status = Job.start_all(date, shift_id)
    # status has [empty] if all printers are ok or an [array] whit the printers and error messages for passing to modal
    result = render_template('jobs/partial_check.html', status=status)
    return jsonify(result=result)


@job_blueprints.route('/start_one/job_id=<string:job_id>', methods=['GET'])
@requires_login
def start_one(job_id):
    if Job.start_one(job_id):
        return True  # return tem que ser um redirect


@job_blueprints.route('/connectall/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def connect_all(date, shift_id):
    status = Job.connect_all(date, shift_id)
    # status has [empty] if all printers are ok or an [array] whit the printers and error messages for passing to modal
    result = render_template('jobs/partial_check.html', status=status)
    return jsonify(result=result)


@job_blueprints.route('/print_jobs/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def print_jobs(date, shift_id):
    jobs = Job.find_many_by_date_shift(date, shift_id)
    rendered = render_template('jobs/print.html', jobs=jobs)
    config = pdfkit.configuration(wkhtmltopdf="C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe")
    pdf = pdfkit.from_string(rendered, False, configuration=config)
    response = make_response(pdf)
    response.headers['Content-Type'] = 'application/pdf'
    return response


@job_blueprints.route('/check_availability/date=<string:date>shift_id=<string:shift_id>', methods=['GET'])
@requires_login
def check_availability(date, shift_id):
    job_exist = Job.find_many_by_date_shift(date, shift_id)
    if len(job_exist) == 0:
        return jsonify(exist=False)
    else:
        return jsonify(exist=True)

views/projects.py
import re
import datetime

from flask import Blueprint, request, render_template, make_response, redirect, url_for, flash, Markup, current_app
from flask_paginate import Pagination, get_page_parameter
from werkzeug.utils import secure_filename

from models.project import Project
from models.user.decorators import requires_login, requires_admin
from common.utils import Utils
import os

project_blueprints = Blueprint("projects", __name__)

view = {
    "title": "Projects",
    "icon": "fa-puzzle-piece",
    "name": "projects",
    "nav_on": True,
    "search_on": False
}


@project_blueprints.route('/', methods=['GET'])
@requires_login
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)

    per_page = 8
    offset = (page - 1) * per_page if page > 0 else 1

    projects = Project.all(offset, per_page)
    counter = len(Project.all())

    view['title'] = "Projects"
    view['search_on'] = True

    search = False
    q = request.args.get('q')
    if q:
        search = True

    pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                            search=search, record_name='projects')

    return render_template('projects/index.html', projects=projects, pagination=pagination, view=view)


@project_blueprints.route('/search', methods=['POST'])
@requires_login
def search():
    if request.method == 'POST' and request.form['parameter'] != "":
        parameter = request.form['parameter']
        projects = Project.get_by_search(parameter)

        page = request.args.get(get_page_parameter(), type=int, default=1)
        counter = len(projects)
        per_page = counter if counter > 0 else 1
        offset = counter

        view['title'] = "Projects"
        view['search_on'] = True

        search = False
        q = request.args.get('q')
        if q:
            search = True

        pagination = Pagination(page=page, per_page=per_page, css_framework='bootstrap4', offset=offset, total=counter,
                                search=search, record_name='projects')

        return render_template('projects/index.html', projects=projects, pagination=pagination, view=view)
    else:
        return redirect(url_for('projects.index'))


@project_blueprints.route('/new', methods=['GET', 'POST'])
@requires_login
def new_project():
    if request.method == 'POST':
        file = request.files['file']

        temp_path = current_app.config.get('TEMPORAL_FOLDER', '')

        if not os.path.exists(temp_path):
            os.makedirs(temp_path)

        file_url_temp = os.path.join(temp_path, secure_filename(file.filename))
        file.save(file_url_temp)

        name = re.sub('.gcode', '', str(file.filename))
        time = Utils.get_print_time(file_url_temp)
        weight = Utils.get_weight(file_url_temp)

        upd_project = Project.find_one_by("name", name)
        if upd_project:

            upload_path = current_app.config.get('UPLOAD_FOLDER', '')

            if not os.path.exists(upload_path):
                os.makedirs(upload_path)

            file_url = os.path.join(upload_path, secure_filename(file.filename))
            os.replace(file_url_temp, file_url)
            path = file_url

            upd_project.name = name
            upd_project.time = time
            upd_project.weight = weight
            upd_project.path = path

            upd_project.save_to_mongo()
            return "The project was updated!", 200
        else:
            upload_path = current_app.config.get('UPLOAD_FOLDER', '')

            if not os.path.exists(upload_path):
                os.makedirs(upload_path)

            file_url = os.path.join(upload_path, secure_filename(file.filename))
            os.replace(file_url_temp, file_url)
            path = file_url
            Project(name, time, weight, path).save_to_mongo()
            return "Upload project successfully", 200
    else:
        view['title'] = "New Project"
        view['search_on'] = False
        return render_template('projects/dragndrop.html', view=view)


@project_blueprints.route('/edit/<string:project_id>', methods=['GET', 'POST'])
@requires_login
def edit_project(project_id):
    project = Project.get_by_id(project_id)

    if request.method == 'POST':
        project.name = request.form['name']
        project.time = request.form['time']
        project.weight = request.form['weight']
        project.path = request.form['path']

        x_project = Project.find_one_by("name", project.name)
        if x_project is not None:
            if x_project._id != project_id:
                message = Markup('<i class="fa fa-warning"></i> Error: The project cannot be created, already exist.')
                flash(message, 'warning')
                view['title'] = "Edit project"
                view['search_on'] = False
                return render_template('projects/edit_project.html', project=project, view=view)

        project.save_to_mongo()
        flash('The project was updated!', 'success')
        return redirect(url_for('projects.index'))
    else:
        view['title'] = "Edit project"
        view['search_on'] = False
        return render_template('projects/edit_project.html', project=project, view=view)


@project_blueprints.route('/delete/<string:project_id>', methods=['GET'])
@requires_login
@requires_admin
def remove_project(project_id):
    project = Project.get_by_id(project_id)
    file_url = project.path
    os.remove(file_url)
    project.remove_from_mongo()
    flash('The project was deleted!', 'danger')
    return redirect(url_for('projects.index'))

templates/jobs/edit_job.html
{% extends "base.html" %}
{% block  content%}
    <section class="add-job-form">
        <form method="post">
            <div class="form-row">
            <div class="form-group input-group col-md-4">
            <input type='text' name="date" autocomplete="off" class="form-control" placeholder="DATE" id='date' value="{{job.date}}" disabled/>
            <div class="input-group-append">
                <span class="input-group-text">
                    <span class="fa fa-calendar"></span>
                </span>
            </div>
            </div>
            <div class="form-group input-group col-md-5">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="shift_id">Shift</label>
                </div>
                <select class="custom-select" name="shift_id" id="shift_id" disabled>
                  <option value="job.shift_id" disabled selected>{{job.shift.desc}}</option>
                </select>
                <input class="form-control" type="text" value="{{job.shift_id}}" name="shift_id" hidden/>
            </div>

            <section>
                <div class="list-group list-group-flush mb-3">
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Printer</th>
                          <th scope="col">Order_id</th>
                          <th scope="col">Project</th>
                          <th scope="col">Color</th>
                          <th scope="col">OBS</th>
                          <th scope="col">Status</th>
                        </tr>
                      </thead>
                      <tbody>                  
                        <tr>
                          <th scope="row">{{ job.printer.name }}
                          <input class="form-control" type="text" value="{{job.printer_id}}" name="printer_id" hidden/>
                          </th>

                          <td>
                            <div class="form-group input-group col">
                                <input class="form-control pr{{job._id}}" type="text" value="{{job.order_id}}" name="order_id" placeholder="Order_id" required/>
                            </div>
                          </td>
                          <td>
                              <div class="form-group input-group">
                                <select class="selectpicker pr{{job._id}}" data-live-search="true" name="project_id" required>
                                  {% if job.project_id != None %}
                                    <option value="{{job.project_id}}" selected>{{job.project.name}}</option>
                                  {% else %}
                                    <option value="" selected disabled>Choose...</option>
                                  {% endif %}
                                  {% for project in projects | sort(attribute='path') | sort(attribute='name')  %}
                                  <option value="{{project._id}}">{{project.name}}</option>
                                  {% endfor %}
                                </select>
                            </div>
                          </td>
                          <td>
                               <div class="form-group input-group">
                                <select class="selectpicker pr{{job._id}}" data-live-search="true" name="filament_id" required>
                                  {% if job.filament_id != None %}
                                    <option value="{{job.filament_id}}" selected>{{job.filament.name}}</option>
                                  {% else %}
                                    <option value="" selected disabled>Choose...</option>
                                  {% endif %}
                                  {% for filament in filaments | sort(attribute='cor')  %}
                                  <option value="{{filament._id}}">{{filament.name}}</option>
                                  {% endfor %}
                                </select>
                            </div>
                          </td>
                          <td>
                              <div class="form-group input-group col">
                                <input id="pr16" class="form-control pr{{job._id}}" type="text" value="{{job.obs}}" name="obs" placeholder="Observations"/>
                            </div>
                          </td>
                          <td>
                            <div class="form-group input-group col">
                                <input class="status" type="checkbox" data-id="pr{{job._id}}" checked data-toggle="toggle" data-on="on" data-off="off" name="status" data-onstyle="success">
                            </div>
                          </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </section>

            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-secondary" href="{{url_for('jobs.index')}}"> Cancel </a>
        </form>
    </section>
   <script type="text/javascript">
    $(function() {
        $('.status').change(function() {
         if ($(this).prop('checked')) {
            var id = $(this).attr('data-id');
            $('.'+id).prop( "disabled", false );
         } else {
             var id = $(this).attr('data-id');
             $('.'+id).prop( "disabled", true );
         }
    })
  })

    </script>
{% endblock %}

templates/jobs/index.html
{% extends "base.html" %}
{% block  content%}
   <section>
       <!-- THE MODAL WE WILL BE USING -->
          <div class="modal fade" id="modal-check">
            <div class="modal-dialog">
              <div class="modal-content">
                  <div class="modal-header">
                    <h6 class="modal-title text-secondary">Checking job status</h6>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body p-0">
                  </div>
              </div>
            </div>
          </div>
       <!-- END MODAL -->

        <div class="list-group list-group-flush mb-3">
          <div id="accordion">
           {% set count = namespace(value=1) %}
           {% for grouper, job in jobs|groupby('date')|sort(attribute='grouper', reverse = True) %}
              {% set outer_loop = loop %}
                {% for grouper2, items in job|groupby('shift_id')|sort(reverse = True) %}
                  {% if outer_loop.index > start and count.value <= pagination.per_page %}
                    {% set count.value = count.value + 1 %}
                      <div class="card mb-1 accordion-list-success">
                        <div class="card-header" id='heading{{ job._id }}'>
                          <div class="pull-left mb-0 col-md-6 ml-0 pl-0" data-toggle="collapse" data-target='#collapse{{grouper}}{{grouper2}}' aria-expanded="false" aria-controls='collapse{{grouper}}{{grouper2}}'>
                            <i style="font-size: 28px" class="fa fa-file-text-o fa-2x p-1 mr-3 float-left text-white" aria-hidden="true"></i>
                            <a class="btn btn-link text-left">
                              <i aria-hidden="true"></i> {{grouper}} {{items[0].shift.desc}}
                            </a>
                          </div>
                             <div id="options" class="col-md-6 float-right text-right mb-0 mt-1">
                                 <span><a title="heat" class="btn btn-warning btn-sm text-white conf-heat" href="{{url_for('jobs.heat_printers', date=grouper, shift_id=grouper2)}}"><i class="fa fa-fire" aria-hidden="true"></i></a></span>
                                 <span><a title="start" class="btn btn-success btn-sm start text-white" data-date="{{grouper}}" data-shift="{{grouper2}}"><i class="fa fa-play" aria-hidden="true"></i></a></span>
                                 <span><a target="_blank" title="print" class="btn btn-secondary btn-sm" href="{{url_for('jobs.print_jobs', date=grouper, shift_id=grouper2)}}"><i class="fa fa-print" aria-hidden="true"></i></a></span>
                                 <span><a title="delete" data-id='date={{grouper}}shift_id={{grouper2}}' class="btn btn-danger btn-sm text-white conf-delete"><i class="fa fa-trash" aria-hidden="true"></i></a></span>
                             </div>
                        </div>
                        <div id='collapse{{grouper}}{{grouper2}}' class="collapse mb-2" aria-labelledby='heading{{job.date}}{{job.shift_id}}' data-parent="#accordion">
                          <div class="card-body">
                              <table class="table table-bordered table-sm table-hover">
                                  <thead class="thead-dark">
                                    <tr>
                                      <th scope="col">PRINTER</th>
                                      <th scope="col">ORDER_ID</th>
                                      <th scope="col">PROJECT</th>
                                      <th scope="col">COLOR</th>
                                      <th scope="col">OBS</th>
                                      {% if grouper >= now %}
                                        <th scope="col"></th>
                                      {% endif %}
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {% for item in items | sort(attribute='printer.name')%}
                                      {% if item.status %}
                                        <tr>
                                      {% else %}
                                        <tr class="bg-inactive">
                                      {% endif %}
                                          <th scope="row">{{item.printer.name}}</th>
                                          <td>{{item.order_id}}</td>
                                          <td>{{item.project.name}}</td>
                                          <td>{{item.filament.name}}</td>
                                          <td>{{item.obs}}</td>
                                          {% if item.date >= now %}
                                            <td><span><a title="edit" class="btn btn-primary btn-sm" href="{{url_for('jobs.edit_job', job_id=item._id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a></span></td>
                                          {% endif %}
                                        </tr>
                                    {% endfor %}
                                  </tbody>
                                </table>
                          </div>
                        </div>
                      </div>
                  {% endif %}
                {% endfor %}
            {% endfor %}
            </div>
        </div>
         <a class="btn btn-success" href="{{url_for('jobs.new_job')}}"> Create New </a>
         <span class="pull-right">{{ pagination.links }}</span>
    </section>

<script type="text/javascript" src="{{ url_for('static', filename='js/btn-actions.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/loading.js') }}"></script>
<script type="text/javascript">
  $(function () {

  $(".start").click(function () {
      var date = $(this).data('date');
      var shift = $(this).data('shift');
    $.ajax({
      type: 'get',
      dataType: 'json',
      cache: false,
      headers: { "cache-control": "no-cache" },
      url: '/jobs/start/date='+date+'shift_id='+shift,
      beforeSend: function () {
        DarkenPageWithLoading();
      },
      success: function (data) {
        LightenPage();
        $("#modal-check").modal("show");
        $("#modal-check .modal-body").html(data.result);
      }
    });
  });

});

</script>
{% endblock %}

templates/jobs/partial_check.html
<section>
 {% if status[0] is defined %}
    <table class="table table-borderless table-sm">
          <thead class="thead-dark">
            <tr>
              <th scope="col">PRINTER</th>
              <th scope="col">PROJECT</th>
              <th scope="col">STATUS</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
             {% for job in status %}
                <tr class="border-bottom">
                  <td><a href="{{job[0].printer_url}}" target="_blank" class="text-black"><i class="fa fa-print"></i> {{job[0].printer_name}}</a></td>
                  <td>{{job[0].job_name}}</td>
                  <td>{{job[0].error}}</td>
                  {% if job[0].error == "File not found!" %}
                    <td><span><a title="edit" class="btn btn-primary btn-sm" href="{{url_for('projects.edit_project', project_id=job[0].project_id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a></span></td>
                  {% endif %}
                </tr>
            {% endfor %}
          </tbody>
    </table>


    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a data-date="{{status[0][0].job_date}}" data-shift="{{status[0][0].job_shift}}" class="btn btn-success text-white connectall">Re-Connect All <i class="fa fa-plug"></i></a>
        <a class="btn btn-primary text-white tryagain" data-date="{{status[0][0].job_date}}" data-shift="{{status[0][0].job_shift}}">Try Again <i class="fa fa-repeat"></i></a>
    </div>
 {% else %}
    <h5 class="p-3 text-success"> <i class="fa fa-print"></i> All printers on the list are printing!</h5>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
 {% endif %}
</section>

<script type="text/javascript">
$(".connectall").click(function () {
      var date = $(this).data('date');
      var shift = $(this).data('shift');
    $.ajax({
      type: 'get',
      dataType: 'json',
      cache: false,
      headers: { "cache-control": "no-cache" },
      url: '/jobs/connectall/date='+date+'shift_id='+shift,
      beforeSend: function () {
       DarkenPageWithLoading();
      },
      success: function (data) {
        LightenPage();
        $("#modal-check").modal("show");
        $("#modal-check .modal-body").html(data.result);
      }
    });
  });

  $(".tryagain").click(function () {
      var date = $(this).data('date');
      var shift = $(this).data('shift');
    $.ajax({
      type: 'get',
      dataType: 'json',
      cache: false,
      headers: { "cache-control": "no-cache" },
      url: '/jobs/start/date='+date+'shift_id='+shift,
      beforeSend: function () {
        DarkenPageWithLoading();
      },
      success: function (data) {
        LightenPage();
        $("#modal-check").modal("show");
        $("#modal-check .modal-body").html(data.result);
      }
    });
  });

</script>

templates/jobs/print.html
{% extends "base.html" %}
{% block  content%}
    <center><img class="p-4" src="{{ static('images/casaz_logo_black.png', pdf=True) }}" height="130px"></center>
     <table class="table">
       <th scope="row" style="border-top:0; font-size: 18px; font-weight: 200">Formulário da produção</th>
       <th scope="row" style="border: 1px solid #000; text-align: center; font-size: 18px">{{ jobs[0].date }}</th>
       <th scope="row" style="border: 1px solid #000; background-color: #000000; color: #FFF; text-align: center; font-size: 18px">{{ jobs[0].shift.desc }}</th>
     </table>
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th scope="col">PRINTER</th>
          <th scope="col">ORDER_ID</th>
          <th scope="col">PROJECT</th>
          <th scope="col">COLOR</th>
          <th scope="col">OBS</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs | sort(attribute='printer.name')%}
        <tr>
          <th scope="row">{{job.printer.name}}</th>
          <td>{{job.order_id}}</td>
          <td>{{job.project.name}}</td>
          <td>{{job.filament.name}}</td>
          <td>{{job.obs}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock %}